package com.trimergo.datamodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class jbpmDMContact implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "First Name")
   private java.lang.String firstName;
   @org.kie.api.definition.type.Label(value = "Last Name")
   private java.lang.String lastName;
   @org.kie.api.definition.type.Label(value = "Number")
   private java.lang.String number;

   public jbpmDMContact()
   {
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public java.lang.String getNumber()
   {
      return this.number;
   }

   public void setNumber(java.lang.String number)
   {
      this.number = number;
   }

   public jbpmDMContact(java.lang.String firstName, java.lang.String lastName,
         java.lang.String number)
   {
      this.firstName = firstName;
      this.lastName = lastName;
      this.number = number;
   }

}