package com.trimergo.datamodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class JbpmDMBusinessPartner implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label("Number")
   private java.lang.String number;
   @org.kie.api.definition.type.Label("Description")
   private java.lang.String description;
   @org.kie.api.definition.type.Label("Id")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Contact")
   private com.trimergo.datamodel.jbpmDMContact contact;

   public JbpmDMBusinessPartner()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getNumber()
   {
      return this.number;
   }

   public void setNumber(java.lang.String number)
   {
      this.number = number;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public com.trimergo.datamodel.jbpmDMContact getContact()
   {
      return this.contact;
   }

   public void setContact(com.trimergo.datamodel.jbpmDMContact contact)
   {
      this.contact = contact;
   }

   public JbpmDMBusinessPartner(java.lang.String name, java.lang.String number,
         java.lang.String description, java.lang.Long id,
         com.trimergo.datamodel.jbpmDMContact contact)
   {
      this.name = name;
      this.number = number;
      this.description = description;
      this.id = id;
      this.contact = contact;
   }

}